version: '3'
services:
  api-testeJson:
    image: node
    container_name: api-json
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/app
    command: bash -c "cd /home/node/app && npm run dev"
    networks:
      system-network:
        ipv4_address: 15.10.0.11
networks:
  system-network:
    driver: bridge
    ipam:
      config:
        - subnet: 15.10.0.0/24